### ISSUE TITLE
PeepOpen locks up MacVim if used to open the first file in a window

### ISSUE THREAD

**Issue by devjj** [topfunky/PeepOpen-Issues#100]
1. Open MacVim to an empty editor window.
2. Activate PeepOpen.
3. Pick a file.
4. Watch MacVim lock up.

After this happens I have to drop to the terminal to manually kill all Vim processes.

**Comment by ddemaree** [comment]
+1. I'm having the same problem. This also seems to happen if the file you're opening has a recoverable .swp file. The MacVim UI locks up, quitting works, but at least one Vim process is left behind.

**Comment by ivar** [comment]
This is seriously negatively affecting me too. I'd love to see it fixed - more info is in a duplicate issue report see #127

**Comment by adamlogic** [comment]
This is not a bug with PeepOpen, but rather MacVim, and it was fixed [here](http://github.com/b4winckler/macvim/commit/f4e9d096f28b055839a24df57e8b46a0897ba45b).  The fix hasn't made it into a released version of MacVim yet, so you have to built it yourself using the instructions [here](http://github.com/b4winckler/macvim/wiki).

**Comment by b4winckler** [comment]
I have just pushed a [potential fix](http://github.com/b4winckler/macvim/commit/be8446006b1467717e17c60a94a6bed3d7abb1c1) to the MacVim repo.  Send me a message on GitHub if you'd like a (10.6) binary to test.

Note that the commit adamlogic linked to is a fix for another problem (specifically, it fixes problems related to using zsh).

**Comment by adamlogic** [comment]
Admittedly, I didn't fully understand the fix that I linked to, but I know that building MacVim myself did resolve the PeepOpen issue (and I was experiencing the exact same issue with ack.vim).  I'd be interested in testing a binary, but I'm not sure it would be valuable since we wouldn't know which commit actually resolved the issue.

**Comment by b4winckler** [comment]
The bug seems to be timing related so it is hard to understand why it appears in the first place.  Building your own binary could have resulted in some timing changes during runtime which caused the problem to go away for you -- I don't know.

I did find a problematic spot in the way MacVim passes input to Vim which would lead to lock ups similar to what PeepOpen users have reported.  The commit I linked to fixes this specific problem and my guess is that it will fix the PeepOpen issue as well.  We'll have to wait and see.

**Comment by b4winckler** [comment]
I have built a new snapshot (build 54) that everybody who are affected by this issue should try. Grab it from the [MacVim downloads](http://github.com/b4winckler/macvim/downloads). If you have any problems, please let me know on the [vim_mac](http://groups.google.com/group/vim_mac) Google group.

**Comment by topfunky** [comment]
MacVim Snapshot 56 and better are much smoother and I haven't been able to get them to lock up at all. Try it and it should fix this problem.
