### ISSUE TITLE
Opens new frame - Emacs 23.x

### ISSUE THREAD

**Issue by gregnewman** [topfunky/PeepOpen-Issues#13]
Using Emacs 23.x compiled from source.

When selecting files to open it opens a new frame instead of a new buffer in the current frame.

I saw another issue filed similarly but that ticket referenced a window which is incorrect.  Since that issue was for CarbonEmacs I thought I'd open a 23.x specific issue.

**Comment by topfunky** [comment]
You're right...this is about a frame, not a window. This is an important bug and I hope to get it working smoothly soon.

**Comment by mwilliams** [comment]
For the Cocoa build of Emacs 23, this did the trick

```
(setq ns-pop-up-frames nil)
```

**Comment by gregnewman** [comment]
@mwilliams…
Thanks! that did it.

@topfunky, maybe just update the emacs documentation with this?

**Comment by fullofcaffeine** [comment]
@topfunky Great work on PeepOpen. I have been using gpicker, which is basically an ugly (and slightly slower, since it needs to re-open the app everytime) version PeepOpen (besides being opensource too). It follows, I think, the same algorithm (I get virtually the same results when I try the search strings on both pickers) and a similar model of integration. However, gpicker does open the files in a buffer in the same window and does not create a new frame. You might want to take a look at the code. Check http://www.fullofcaffeine.com/2010/01/01/gpicker-on-osx/ on instructions for building it on OSX. The repo is http://github.com/alk/gpicker. All credits go to Aliaksey Kandratsenka.

**Comment by sunny36** [comment]
Experienced the same issue but the solution by @mwilliams works.

**Comment by topfunky** [comment]
The ns-pop-up-frames configuration is now mentioned in the Help documents in 0.2.0.
