### ISSUE TITLE
PeepOpen Window Doesn't Open

### ISSUE THREAD

**Issue by takaaki** [topfunky/PeepOpen-Issues#16]
I'm using the latest version of MacVim. The PeepOpen Window stopped working when I press `<leadler>p`.

The console outputs the following Ruby errors:

```
4/14/10 11:42:08 AM PeepOpen[93417] undefined method `map' for nil:NilClass
```

**Comment by alloy** [comment]
I suggest that, if possible, you try to run the application with the current MacRuby trunk. Which would log a bit more useful info as to where the exception actually occurred.

**Comment by topfunky** [comment]
In some cases, MacVim's current directory is being switched back to "/" after a file is opened from PeepOpen. Could you try again, but post the output of :pwd here?

Also, make sure that at least one file is open in MacVim. It seems to launch extra zombie processes if no files are open. Figuring this out is a high priority and I'm working on it now.

**Comment by airblade** [comment]
I get this too.  The first time I use `<leader>p` it works but changes `:pwd` to `/`.  Subsequent `<leader>p` invocations give the undefined method 'map' error.

I suspect this is because PeepOpen uses `mvim --remote somefile` instead of `open -a MacVim somefile`.  The former will fire up MacVim in the root directory and not heed the user's MacVim preferences for file opening.

**Comment by topfunky** [comment]
I was initially advised by experienced Vim users and Ruby implementors to not use "open -a MacVim filename", but I think it might be a better solution now. 

However, it will require that people change their MacVim preferences (in the GUI) if they want files to open in the same window instead of a new tab.

**Comment by takaaki** [comment]
I've noticed I have many "Vim" processes in Activity Monitor after using MacVim. I can't always reproduce the bug. For the time being, it may be useful to write what information is needed to write a report.
- How did you invoke MacVim? What command in Terminal? Or Did you double-click the icon on Finder or in the Dock?
- Did you make sure you opened at least one file before using PeepOpen?
- If you have any issues, run `:pwd` to tell where you are and if you are in the place you are supposed to be at.
- Open up Activity Monitor and search for "Vim". Do you see the "Vim" processes you don't expect?
- Open up Console and search for "peep", do you see anything?

Sorry for my initial unprofessional report. I'll keep eyes on this _if_ this happens to me nex time.

**Comment by airblade** [comment]
Takaaki, forgive me if you already know this -- you would expect to see many Vim processes in Activity Monitor while (though not after you have finished) using MacVim.

[This](http://groups.google.com/group/vim_mac/msg/a3dc10b949984353) explains MacVim's process management.
