### ISSUE TITLE
Add a File Tree

### ISSUE THREAD

**Issue by cleverdevil** [topfunky/PeepOpen-Issues#221]
I am a longtime TextMate user switching to MacVim. PeepOpen almost gets me there, but I still miss a project drawer with pretty expandable file free. No, NerdTree is not good enough in any shape or form.

It would be fantastic if the "Open With" window in PeepOpen could be optionally replaced with a filterable project tree for the active project. As I type, the tree would simply filter out non-matches. If I didn't want to type, I could simply navigate through the hierarchy with my mouse until I find the file I want.

**Comment by topfunky** [comment]
Thanks for the suggestion, but this is pretty far from the problem PeepOpen was written to solve. PeepOpen is all about showing files by simple search rather than requiring mouse input or a hierarchical tree.

We're definitely thinking about better ways to visualize the filesystem but currently don't have plans to use a file tree.

But this sounds like a great idea for a separate project or a new tool!
