### ISSUE TITLE
Error while opening PeepOpen

### ISSUE THREAD

**Issue by sriprasanna** [topfunky/PeepOpen-Issues#29]
I downloaded and tried to open PeepOpen and I keep getting "Application unexpectedly quit". This is the error report I got. 

Process:         PeepOpen [35550]
Path:            /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
Identifier:      com.topfunky.PeepOpen
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [200]

Interval Since Last Report:          190 sec
Crashes Since Last Report:           3
Per-App Interval Since Last Report:  0 sec
Per-App Crashes Since Last Report:   3

Date/Time:       2010-04-18 21:08:09.779 +0530
OS Version:      Mac OS X 10.5.8 (9L31a)
Report Version:  6
Anonymous UUID:  8697A798-8C4F-4ADF-988F-53CFA8E4BC16

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.dylib
  Referenced from: /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
  Reason: no suitable image found.  Did find:
    /Applications/PeepOpen.app/Contents/MacOS/../Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.dylib: unknown required load command 0x80000022
    /Applications/PeepOpen.app/Contents/MacOS/../Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.dylib: unknown required load command 0x80000022

**Comment by urbankid** [comment]
I also get an error when attempting to open PeepOpen:

The application PeepOpen quit unexpectedly.

Problem details:
Process:         PeepOpen [615]
Path:            /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
Identifier:      com.topfunky.PeepOpen
Version:         ??? (???)
Code Type:       X86-64 (Native)
Parent Process:  launchd [325]

Interval Since Last Report:          733 sec
Crashes Since Last Report:           4
Per-App Interval Since Last Report:  0 sec
Per-App Crashes Since Last Report:   4

Date/Time:       2010-04-24 21:45:00.981 +0200
OS Version:      Mac OS X 10.5.8 (9L30)
Report Version:  6
Anonymous UUID:  91D5A198-B4C4-4D23-84FF-02FB1B21B188

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000002, 0x0000000000000000
Crashed Thread:  0

Dyld Error Message:
  Library not loaded: @executable_path/../Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.dylib
  Referenced from: /Applications/PeepOpen.app/Contents/MacOS/PeepOpen
  Reason: no suitable image found.  Did find:
    /Applications/PeepOpen.app/Contents/MacOS/../Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.dylib: unknown required load command 0x80000022
    /Applications/PeepOpen.app/Contents/MacOS/../Frameworks/MacRuby.framework/Versions/0.5/usr/lib/libmacruby.dylib: unknown required load command 0x80000022

---

System configuration:
Model: MacBookPro2,2, BootROM MBP22.00A5.B07, 2 processors, Intel Core 2 Duo, 2.33 GHz, 2 GB
Graphics: kHW_ATIr520Item, ATY,RadeonX1600, spdisplays_pcie_device, 256 MB
Memory Module: global_name
AirPort: spairport_wireless_card_type_airport_extreme (0x168C, 0x87), 1.4.16.2
Bluetooth: Version 2.1.9f10, 2 service, 0 devices, 1 incoming serial ports
Network Service: AirPort, AirPort, en1
Network Service: Parallels Shared Networking Adapter, Ethernet, en2
Network Service: Parallels Host-Only Networking Adapter, Ethernet, en3
Serial ATA Device: FUJITSU MHW2120BH, 111.79 GB
Parallel ATA Device: HL-DT-ST DVDRW GWA4080MA
USB Device: iPhone, (null) mA
USB Device: Built-in iSight, (null) mA
USB Device: IR Receiver, (null) mA
USB Device: Apple Optical USB Mouse, (null) mA
USB Device: Apple Internal Keyboard / Trackpad, (null) mA
USB Device: Bluetooth USB Host Controller, (null) mA

**Comment by urbankid** [comment]
Hi again,
Now I know why PeepOpen doesn't work on my system. I can't remember reading this when I bought it, maybe it has been added later or maybe I was just to eager to bother and read the whole description, but the minimum requirements are clear:

PeepOpen is a file navigation application that works with TextMate, MacVim, and Carbon Emacs (Mac OS X Snow Leopard on 64-bit Intel required, support for other editors is coming soon).

So I guess I have to wait until the new machine arrive :(

**Comment by topfunky** [comment]
Yes, Snow Leopard 10.6 is required, as you noted.
