### ISSUE TITLE
Where is PeepOpen?

### ISSUE THREAD

**Issue by jordwalke** [topfunky/PeepOpen-Issues#294]
I can't find a link to it anywhere anymore. Care to open source it?

**Comment by iansinnott** [comment]
I second this. I see this issue is only a few days old, so maybe peepopen was just recently taken down. Open sourcing the project would be great. Putting it back up for sale wouldn't be as good but still something. Either sell it or let the community handle continued development and support, but don't just throw it away.

**Comment by jordwalke** [comment]
It would be such a waste to throw it away - I believe PeepOpen disappeared several months ago. You can try asking on PeepCode's Facebook page too.

**Comment by topfunky** [comment]
We'll be open sourcing it soon. In the meantime (before December 31 2013), download it free here:

https://peepcode.com/system/apps/PeepOpen/PeepOpen.dmg

**Comment by topfunky** [comment]
Open sourced: https://github.com/topfunky/PeepOpen

Needs help to upgrade to a current build of Xcode, MacRuby/RubyMotion, etc.

**Comment by jordwalke** [comment]
Fast turnaround. Great work!

**Comment by iansinnott** [comment]
Excellent! Yes, thanks for the very fast turnaround

**Comment by fullofcaffeine** [comment]
@topfunky Awesome. I love Peepopen (I bought it when it you firstly released it). And I still actively use it. Nice to see it being open sourced! 

By the way, I use a similar solution on Linux, and it works very well (although the GUI is not as polished). It's called gpicker - https://github.com/alk/gpicker.
