### ISSUE TITLE
MacVim documents should open on the same buffer, or into a new tab

### ISSUE THREAD

**Issue by oscardelben** [topfunky/PeepOpen-Issues#56]
Right now when using the peepopen application with macvim, files are opened in a new window. This is annoying. In my opinion they should open on the same buffer (shortcut:o) or in a new tab (shortcut:t). Is this possible?

**Comment by iamjwc** [comment]
I'm also having this problem. It worked fine before I upgraded to the current version.

**Comment by priyav** [comment]
Change your MacVim preferences to "Open new files in the same window".
This might fix the problem.

**Comment by iamjwc** [comment]
This makes it a little better, but not perfect. It would be best if it worked like it used to.
- Open new tab
- +p to open PeepOpen
- choose file
- Selected file gets opened in that tab.

This way, it allows you to open a file in an existing tab, as well. Otherwise every time you open a new file, it just makes another tab.

**Comment by xaviershay** [comment]
In macvim preferences, select "Open files from applications: in the current window, and set the arglist"

**Comment by iamjwc** [comment]
Aaanndd there you have it.

**Comment by topfunky** [comment]
This should be fixed since v0.2.0, with the preferences fix mentioned by Xavier Shay (also noted in the PeepOpen help page for MacVim). It requires a recent snapshot of MacVim (I use 52).
