### ISSUE TITLE
Clicking table should open file

### ISSUE THREAD

**Issue by topfunky** [topfunky/PeepOpen-Issues#59]
Problem:

Clicking the name of a file in the table view doesn't do anything. Even though it's preferred to operate the app with the keyboard, mouse interactions should be honored, too.

Expected Behavior:

Clicking a row with a filename should open that filename in the editor of choice.

**Comment by jondkinney** [comment]
Not only that but it disables the ability to subsequently open the file from the keyboard. You have to re-do the cmd-T to get the dialog open again and then make your selection with the keyboard.

**Comment by cpb** [comment]
j2fly, try:

click, tab, return

I've got an apple bluetooth keyboard so the return isn't much of a thumb reach for me

Was going to make a ticket but found this one!

**Comment by chrisb** [comment]
I second this.

**Comment by tspore** [comment]
I usually 90% of the time open files with my return key. But today I kept clicking with a mouse on a file to open, and nothing happened. I was stumped what did I do wrong. Is my little world falling apart :{} All in all I think that using the keyboard is great most of the time, but I just happened to click with a mouse and discovered it didn't work. So that was a bit odd to me. 
This isn't huge to me, I think that having the cmd - T remember the last search would be more important. But letting a mouse click to open would be nice. 
Overall a great little product I'm using it all the time now.

**Comment by diabolo** [comment]
Just been bitten by the mouse clicking issue. Basically it makes you think PeepOpen is unusable. Fortunately I came here and found this thread, but if I hadn't then I would have a very low opinion of PeepOpen and just binned it. Think this should be a very high priority fix,  because clicking on an entry actually breaks the application

**Comment by dougjohnston** [comment]
Similar to others, I use the keyboard 90% of the time, but it'd be nice to navigate with the mouse as well.  Currently a click turns the row green, making me _think_ I've selected the file, but instead, I've rendered PeepOpen useless.  I can either close and reopen or click in the search box to re-enable keyboard navigation.  Both are unexpected behaviors.  It'd be great to see a fix for this!

**Comment by electricgraffitti** [comment]
I agree with this. Please Please! make this happen. Ive almost uninstalled peepopen because im constantly clicking on the row i want, only to have to re focus on the top search to get the file to open.

**Comment by kernow** [comment]
How come this hasn't been fixed yet? 7 months old now.

**Comment by markus** [comment]
See also "Click to preview, double click to open" https://github.com/topfunky/PeepOpen-Issues/issues/issue/179

**Comment by topfunky** [comment]
Fixed in 0.3.1. Clicking a row immediately opens that file in your editor.
