### ISSUE TITLE
MacVim crashs after attempting to open a file with peepopen

### ISSUE THREAD

**Issue by oscardelben** [topfunky/PeepOpen-Issues#63]
I don't know why, but after this morning whenever I try to open a file with peeopen, macvim crashes, in the sense that I can't do anything, and I don't even see the file being opened. I can still normally close it without a force quit. I'll try agan later today.

**Comment by oscardelben** [comment]
It seems like it's working perfectly again now. Not sure what happened.

**Comment by topfunky** [comment]
I've occasionally experienced this if no files are open in MacVim. A fix probably entails writing vimscript to be smarter about the current directory.

**Comment by keyneston** [comment]
I just ran into this issue. 

From a terminal I cd into the project root.
Then I ran `mvim .` to open mvim in the current directory.
When trying to use peepopen to open a file from the project vim crashes.

I reproduced this 5-6 times before finding this thread and instead of `mvim .` I ran `mvim Rakefile` which works around the issue.
