### ISSUE TITLE
"Couldn't Find Files"

### ISSUE THREAD

**Issue by dnch** [topfunky/PeepOpen-Issues#95]
Opened a Rails project in Texmate, no documents open, PeepOpen running... Cmd-T:

"Try another directory or see the Project Root Pattern preference in the Advanced tab."

Other rails projects work fine. I haven't changed anything in the Project Root Pattern... am totally stuck.

**Comment by urbankid** [comment]
The same thing happened to me. The current project i'm working with won't load any files. I get the same "Couldn't Find Files".

Since I had problems with TextMate project I'm working opening directly the directory.
With other projects PeepOpen find all files, but just with this one project no files are found.

I've tried everything but with no luck.

So I have decided to uninstall PeepOpen, until this bug is fixed.

**Comment by urbankid** [comment]
Yesterday I decided to delete PeepOpen. I deleted it and worked with TextMate old style and at the end of the day turn off my machine. Today, just for fun, I decided to install it again.

I just opened the project that gave me problems and now it works fine again!

This was a real déjà vu from my old Windows days (turn off and turn on again), but I am really happy to keep PeepOpen ;)

**Comment by topfunky** [comment]
Glad to hear that it worked. We fixed the error behavior in 0.3.1 to show somewhat more informative error messages if files can't be found.
